apiVersion: v1
kind: Service
metadata:
  name: my-go-app-service
  namespace: goapp
  labels:
    app: my-go-app
spec:
  type: ClusterIP
  ports:
  - name: my-go-app
    port: 9096
    targetPort: 9096
  selector:
    app: my-go-app

